2019-04-02 11:01:30,354 - Exception on / [GET]
Traceback (most recent call last):
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 38, in main2
    form = InputForm()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask_wtf/csrf.py", line 121, in _get_config
    raise KeyError(message)
KeyError: 'A secret key is required to use CSRF.'
2019-04-02 12:02:55,036 - Exception on / [GET]
Traceback (most recent call last):
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 53, in main2
    return render_template('amr.html',form=form)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: amr.html
2019-04-02 12:03:06,036 - Exception on / [GET]
Traceback (most recent call last):
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 53, in main2
    return render_template('amr.html',form=form)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: amr.html
2019-04-02 12:04:36,915 - Exception on / [GET]
Traceback (most recent call last):
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 53, in main2
    return render_template('amr.html',form=form)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/disk/ocean/mdamonte/miniconda/envs/gentest/lib/python3.6/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: amr.html
